stages:
  - buildimage
  - deplyk8s

variables:
  NAMESPACE: joglo
  APP_NAME: joglo-auth


deploy_dev:
  only:
    - master
  tags:
    - merapi
  stage: buildimage
  image: docker:24.0.5
  variables:
    DOCKER_HOST: tcp://192.168.88.200:2375/
    DOCKER_DRIVER: overlay2
  script:
    - echo "Deploy ke server merapi"
    - mkdir -p /root/.docker
    - cp $HARBOR_CRED /root/.docker/config.json
    - cp $ENV app.env
    - docker build -t harbor.merapi.javan.id/$NAMESPACE/$APP_NAME:$CI_COMMIT_SHORT_SHA .
    - docker push harbor.merapi.javan.id/$NAMESPACE/$APP_NAME:$CI_COMMIT_SHORT_SHA

deployk8s:
  only:
    - master
  tags:
    - merapi
  stage: deplyk8s
  image: harbor.merapi.javan.id/tools/helm
  script:
    - cp $KUBERNETEST_MERAPI_ENV  /root/.kube/config
    - echo "192.168.88.200 k8s-master" >> /etc/hosts
    - chmod 600 ~/.kube/config
    - helm upgrade --install $APP_NAME helm/ --namespace $NAMESPACE --create-namespace --set image.tag=$CI_COMMIT_SHORT_SHA -f helm/values.yaml
